name: deploy-on-server
on: 
  push: 
    branches: [master]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://sijusamson.com/public_html/personal_website/
        ftp-username: sijusn51
        ftp-password: 9T9rRoA0V9r4!0+0